sudo: required
services:
  - docker

before_install:
  - docker build -t thomaspragma/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thomaspragma/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "udemy-docker"
  env: "Udemy-docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-629066513793"
  bucket_path: "udemy-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"